# Generated by Django 5.2.5 on 2025-08-27 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Transport', 'Transport'), ('Entertainment', 'Entertainment')], max_length=32),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
